### Login
POST https://dev.api.jego.cm/v1/auth/login
Content-Type: application/json

{
  "email": "admin@jego.cm",
  "password": "123456"
}


### Register
POST http://localhost:3333/v1/auth/register
Content-Type: application/json

{
  "firstName": "Ron",
  "lastName": "Coder",
  "email": "ronaldtchuekou@gmail.com",
  "password": "password"
}

### Toggle block user
PATCH http://localhost:3333/v1/users/70f6dec3-90e7-48ab-b89f-ee3415039170/toggle-block
Content-Type: application/json


### Get jobs by company id
GET http://localhost:3333/v1/jobs/company/7b8fd03c-5fd4-458d-983f-55c631dc1906
Content-Type: application/json
